name: "Hello GitHub Action"

on: 
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_dispatch:

jobs:
  Hello-job:
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout do codigo
          uses: actions/checkout@v4

        - name: Executar Hello Word
          run: echo " Hello Github Actions" 
        - name: Mostrar informações do sistema
          run: |
            echo "Sistema Operacional: ${{ runner.os}}"
            echo "Diretorio Atual: $(pwd)"
            echo "Data Atual: $(date)"
            echo "Usuario Atual: $(whoami)"

        - name: Listar Arquivos dos repositorios 
          run: ls -la
        - name: Comandos múltiplos 
          run: |
            echo "Este sou eu tentando aprender github actions"
            echo "workflow executando com sucesso"
            echo "Pronto para os AAAAAAAAAAAAAAAA"